# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questionsort', models.IntegerField()),
                ('details', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'consult_twentyeight',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('ordertime', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=128)),
                ('expressbrand', models.CharField(max_length=128)),
                ('paywayid', models.IntegerField()),
                ('integral', models.IntegerField()),
                ('phone', models.CharField(max_length=128)),
                ('orderstatus', models.IntegerField()),
                ('getgoodstime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_twenty',
            },
        ),
        migrations.CreateModel(
            name='Orderchild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField()),
                ('goodid', models.IntegerField()),
                ('goodcount', models.IntegerField()),
                ('goodmoney', models.IntegerField()),
                ('goodmoneycount', models.IntegerField()),
            ],
            options={
                'db_table': 'orderchild_twentyone',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField()),
                ('clientreturntime', models.DateTimeField(auto_now_add=True)),
                ('retailersreturntime', models.DateTimeField(blank=True, null=True)),
                ('bankdotime', models.DateTimeField(blank=True, null=True)),
                ('returnoktime', models.DateTimeField(blank=True, null=True)),
                ('returntype', models.IntegerField(blank=True, null=True)),
                ('returnreason', models.CharField(blank=True, max_length=128, null=True)),
                ('returnmoney', models.IntegerField(blank=True, null=True)),
                ('returndetails', models.CharField(blank=True, max_length=256, null=True)),
                ('picturepath1', models.CharField(blank=True, max_length=256, null=True)),
                ('picturepath2', models.CharField(blank=True, max_length=256, null=True)),
                ('picturepath3', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'return_twentytwo',
            },
        ),
        migrations.CreateModel(
            name='Shopcart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('goodsid', models.IntegerField()),
                ('goodscount', models.IntegerField()),
                ('goodsprice', models.IntegerField()),
                ('goodsaddtime', models.DateTimeField()),
                ('discount', models.IntegerField()),
            ],
            options={
                'db_table': 'shopcart_twentyfour',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remains', models.IntegerField(default=0)),
                ('importprice', models.IntegerField()),
                ('outportprice', models.IntegerField()),
            ],
            options={
                'db_table': 'stock_twentythree',
            },
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questionsort', models.IntegerField()),
                ('details', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'suggest_twentynine',
            },
        ),
    ]
