# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertwenty',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordertwenty',
            name='phone',
        ),
        migrations.AddField(
            model_name='ordertwenty',
            name='addressid',
            field=models.IntegerField(default=0),
        ),
    ]
