# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20190704_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertwenty',
            name='remarks',
            field=models.CharField(default='--', max_length=100, null=True),
        ),
    ]
