# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20190702_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertwenty',
            name='addressid',
            field=models.IntegerField(),
        ),
    ]
