# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_ordertwenty_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertwenty',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
