# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20190704_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchildtwentyone',
            name='goodcount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderchildtwentyone',
            name='goodid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderchildtwentyone',
            name='goodmoney',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderchildtwentyone',
            name='goodmoneycount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderchildtwentyone',
            name='orderid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertwenty',
            name='addressid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertwenty',
            name='expressbrandid',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ordertwenty',
            name='integral',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertwenty',
            name='orderstatus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertwenty',
            name='ordertime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertwenty',
            name='paywayid',
            field=models.IntegerField(null=True),
        ),
    ]
