# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-03 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_mobilecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertwenty',
            name='uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
