# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20190705_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchildtwentyone',
            name='cid',
            field=models.IntegerField(default=1),
        ),
    ]
