# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_orderchildtwentyone_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchildtwentyone',
            name='cid',
            field=models.IntegerField(),
        ),
    ]
