# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20190709_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertwenty',
            name='orderstatus',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordertwenty',
            name='paywayid',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
