# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_auto_20190709_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returntwentytwo',
            name='clientreturntime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
