# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_auto_20190709_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertwenty',
            name='ordertime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
