# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-10 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_auto_20190709_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcarttwentyfour',
            name='goodsid',
        ),
        migrations.RemoveField(
            model_name='shopcarttwentyfour',
            name='goodsprice',
        ),
        migrations.AddField(
            model_name='shopcarttwentyfour',
            name='cid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertwenty',
            name='integral',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordertwenty',
            name='ordertime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='shopcarttwentyfour',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopcarttwentyfour',
            name='goodsaddtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
