# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_auto_20190710_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcarttwentyfour',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopcarttwentyfour',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
