# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brandname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'commodity_brand_two',
            },
        ),
        migrations.CreateModel(
            name='CommodityCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentid', models.IntegerField()),
                ('categoryname', models.CharField(max_length=20)),
                ('picture', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'commodity_categories_three',
            },
        ),
        migrations.CreateModel(
            name='CommodityCategoriesTwo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('smallclassesid', models.IntegerField()),
                ('smallclassesattribute', models.CharField(max_length=20)),
                ('weightprice', models.IntegerField()),
            ],
            options={
                'db_table': 'commodity_categories_two_four',
            },
        ),
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preferentialthreshold', models.IntegerField()),
                ('preferentialcontent', models.IntegerField()),
                ('expirationtime', models.DateTimeField()),
                ('usingstate', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'coupons_five',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=50, unique=True)),
                ('discount', models.CharField(default=0, max_length=50)),
                ('picture', models.CharField(max_length=1000)),
                ('attribute', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=128)),
                ('weightprice', models.IntegerField()),
                ('historicalprices', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('goodsstate', models.IntegerField(default=0)),
                ('brandid', models.IntegerField()),
                ('smallclassesid', models.IntegerField()),
                ('classid', models.ForeignKey(db_column='id', default=None, on_delete=django.db.models.deletion.CASCADE, to='Goods.CommodityCategories')),
            ],
            options={
                'db_table': 'goodsone',
            },
        ),
        migrations.CreateModel(
            name='Goodsdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Goodsid', models.IntegerField()),
                ('productclass', models.CharField(max_length=216)),
                ('rawmaterial', models.CharField(max_length=216)),
                ('origin', models.CharField(max_length=216)),
                ('ingredients', models.CharField(max_length=216)),
                ('productspecification', models.CharField(max_length=216)),
                ('shelflife', models.CharField(max_length=216)),
                ('productstandardnumber', models.CharField(max_length=216)),
                ('productionlicensenumber', models.CharField(max_length=216)),
                ('storeway', models.CharField(max_length=216)),
                ('eatway', models.CharField(max_length=216)),
                ('picture1', models.CharField(max_length=128, null=True)),
                ('picture2', models.CharField(max_length=128, null=True)),
                ('picture3', models.CharField(max_length=128, null=True)),
                ('picture4', models.CharField(max_length=128, null=True)),
                ('picture5', models.CharField(max_length=128, null=True)),
                ('picture6', models.CharField(max_length=128, null=True)),
                ('picture7', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'goodsdetails_seven',
            },
        ),
        migrations.CreateModel(
            name='Productevaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodsid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField()),
                ('anonymous', models.IntegerField()),
                ('evaluationimage', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'productevaluation_nine',
            },
        ),
    ]
