# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
