# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_goods_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.CharField(default='件', max_length=20),
        ),
    ]
