# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_auto_20190704_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdetails',
            name='mpicture1',
            field=models.CharField(default=1, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='goodsdetails',
            name='mpicture2',
            field=models.CharField(default=1, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='goodsdetails',
            name='mpicture3',
            field=models.CharField(default=1, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='goodsdetails',
            name='spicture1',
            field=models.CharField(default=1, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='goodsdetails',
            name='spicture2',
            field=models.CharField(default=1, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='goodsdetails',
            name='spicture3',
            field=models.CharField(default=1, max_length=128, null=True),
        ),
    ]
