# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0006_commoditycategoriestwo_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditycategoriestwo',
            name='sort',
            field=models.IntegerField(null=True),
        ),
    ]
