# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0007_auto_20190705_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditybrand',
            name='weightprice',
            field=models.IntegerField(default=0),
        ),
    ]
