# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0008_commoditybrand_weightprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'specification',
            },
        ),
        migrations.RemoveField(
            model_name='commoditybrand',
            name='weightprice',
        ),
        migrations.RemoveField(
            model_name='commoditycategoriestwo',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='commoditycategoriestwo',
            name='weightprice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='inventory',
        ),
        migrations.AddField(
            model_name='commoditycategoriestwo',
            name='brandid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commoditycategoriestwo',
            name='inventory',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='commoditycategoriestwo',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commoditycategoriestwo',
            name='specification_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goods',
            name='attributeid',
            field=models.IntegerField(default=1),
        ),
    ]
