# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0011_auto_20190705_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditycategoriestwo',
            name='historicalprices',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commoditycategoriestwo',
            name='price',
            field=models.IntegerField(),
        ),
    ]
