# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0013_auto_20190705_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditycategoriestwo',
            name='gid',
            field=models.IntegerField(),
        ),
    ]
