# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0014_auto_20190705_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='classid',
        ),
    ]
