# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0015_remove_goods_classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditycategoriestwo',
            name='historicalprices',
            field=models.IntegerField(null=True),
        ),
    ]
