# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-04 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Express_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_name', models.CharField(max_length=10)),
                ('express_price', models.IntegerField(default=8)),
                ('express_phonenumber', models.CharField(max_length=20)),
                ('express_info', models.CharField(max_length=200)),
                ('express_photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'express_company',
            },
        ),
        migrations.CreateModel(
            name='Express_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_id', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('updatetime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('update_info', models.CharField(max_length=100, null=True)),
                ('order_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'express_info',
            },
        ),
        migrations.CreateModel(
            name='Pay_way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_name', models.CharField(max_length=50)),
                ('pay_info', models.CharField(max_length=200)),
                ('pay_photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'pay_way',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('realname', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('pay_password', models.CharField(max_length=128, null=True)),
                ('user_type', models.IntegerField(default=0, null=True)),
                ('certificate', models.CharField(max_length=20, null=True)),
                ('certificate_id', models.CharField(max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('sex', models.CharField(choices=[(1, '男'), (2, '女'), (0, '保密')], default=1, max_length=5, null=True)),
                ('shopping_grade', models.IntegerField(default=0, null=True)),
                ('reg_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('birthday', models.CharField(max_length=20, null=True)),
                ('user_photo', models.CharField(default='/admin/upload/avatar_blank.gif', max_length=100, null=True)),
                ('user_status', models.IntegerField(default=0, null=True)),
                ('vip_level', models.IntegerField(default=0, null=True)),
                ('safety_grade', models.IntegerField(default=0, null=True)),
                ('question1', models.CharField(max_length=50, null=True)),
                ('answer1', models.CharField(max_length=50, null=True)),
                ('question2', models.CharField(max_length=50, null=True)),
                ('answer2', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_password', models.CharField(max_length=128, null=True)),
                ('bankcard_id', models.CharField(default=0, max_length=50, null=True)),
                ('money', models.IntegerField(default=0, null=True)),
                ('alipay_number', models.CharField(max_length=20, null=True)),
                ('wechat_number', models.CharField(max_length=20, null=True)),
                ('useroffer_id', models.CharField(max_length=100, null=True)),
                ('goodoffer_id', models.CharField(max_length=100, null=True)),
                ('used_userofferid', models.CharField(max_length=100, null=True)),
                ('used_goodofferid', models.CharField(max_length=100, null=True)),
                ('integral_id', models.IntegerField(default=1, null=True)),
                ('user', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='User_address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('default_address', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=100, null=True)),
                ('receiver', models.CharField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
        migrations.CreateModel(
            name='User_collection',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField(null=True)),
                ('collection_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'db_table': 'user_collection',
            },
        ),
        migrations.CreateModel(
            name='User_foot',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField()),
                ('isdisplay', models.IntegerField(default=1)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'db_table': 'user_foot',
            },
        ),
        migrations.CreateModel(
            name='User_grade',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('change_source', models.CharField(max_length=50)),
                ('change_number', models.IntegerField(null=True)),
                ('change_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('changed_grade', models.IntegerField(null=True)),
                ('growth_value', models.IntegerField(null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'db_table': 'user_grade',
            },
        ),
        migrations.CreateModel(
            name='User_notice',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('picture_path', models.CharField(max_length=200, null=True)),
                ('sendtime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('tag_path', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'user_notice',
            },
        ),
        migrations.CreateModel(
            name='User_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_content', models.CharField(max_length=200)),
                ('offer_time', models.DateTimeField(null=True)),
                ('offer_door', models.IntegerField(default=100, null=True)),
                ('offer_money', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'user_offer',
            },
        ),
    ]
