# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Express_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_name', models.CharField(max_length=10)),
                ('express_price', models.IntegerField(default=8)),
                ('express_phonenumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'express_company',
            },
        ),
        migrations.CreateModel(
            name='Express_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_id', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('updatetime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('update_info', models.CharField(max_length=100, null=True)),
                ('order_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'express_info',
            },
        ),
        migrations.CreateModel(
            name='User_collections',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField(null=True)),
                ('collection_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_content', models.CharField(max_length=200)),
                ('offer_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('offer_door', models.IntegerField(default=100, null=True)),
                ('offer_money', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'user_offer',
            },
        ),
    ]
