# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-01 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pay_way',
            table='pay_way',
        ),
    ]
