# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-29 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_express_company_express_info_user_collections_user_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_offer',
            name='status',
        ),
        migrations.AddField(
            model_name='user_account',
            name='used_goodofferid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_account',
            name='used_userofferid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='goodoffer_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='useroffer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
