# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-02 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190702_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.CharField(default='/admin/upload/avatar_blank.gif', max_length=100, null=True),
        ),
    ]
