# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190707_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areainfo',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('pid', models.CharField(max_length=6, null=True)),
            ],
            options={
                'db_table': 'areainfo',
            },
        ),
    ]
