# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-02 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190702_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='user',
            field=models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
