# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-28 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('realname', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('pay_password', models.CharField(max_length=128)),
                ('user_type', models.IntegerField(default=0, null=True)),
                ('certificate', models.CharField(max_length=20)),
                ('certificate_id', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[(1, '男'), (2, '女'), (0, '保密')], default=1, max_length=5, null=True)),
                ('shopping_grade', models.IntegerField(default=0, null=True)),
                ('reg_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('birthday', models.CharField(max_length=20, null=True)),
                ('user_status', models.IntegerField(default=0, null=True)),
                ('vip_level', models.IntegerField(default=0, null=True)),
                ('safety_grade', models.IntegerField(default=0, null=True)),
                ('question1', models.CharField(max_length=50, null=True)),
                ('answer1', models.CharField(max_length=50, null=True)),
                ('question2', models.CharField(max_length=50, null=True)),
                ('answer2', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
